Vagrant.configure(2) do |config|  
  config.vm.box = "StefanScherer/windows_10"
  
  config.vm.network "public_network"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.provider "hyperv"
  config.vm.provider "hyperv" do |vb|    
    vb.memory = "4034"
    vb.cpus = 6
  end
  
end