# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.box_version = "1903.0.1906-enterprise"
  config.vm.box_check_update = false
  
  config.vm.provider "virtualbox" do |vb|    
    vb.gui = false
    vb.memory = "8048"
    vb.cpus = 8
  end
  
end
