# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.box_version = "1909.0.2003-enterprise"
  config.vm.box_check_update = false
  
  config.vm.provider "hyperv" do |h|
    h.cpus = 6
    h.memory = 5024
    h.maxmemory = 5024
    h.enable_virtualization_extensions = true
  end

end
